version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  # Create a group of dependencies to be updated together in one pull request
  groups:
     # Specify a name for the group. Used in pull request titles and branch names
     production-dependencies:
        # Define patterns to include dependencies in the group (based on dependency name)
        patterns:
          - "*" # A wildcard that matches all dependencies in the package ecosystem.
  schedule:
    interval: daily
  open-pull-requests-limit: 10
