on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: "26"
      - name: Publish to Hex.pm
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile
          mix compile
          mix hex.build
          mix hex.publish --yes
